config/routes.rb
Rails.application.routes.draw do
  get 'coaching_controller/answer'

  get 'coaching_controller/ask'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coaching_controller_controller.rb
class CoachingControllerController < ApplicationController
  def answer
      @query = params[:query]
  end

  def ask
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaching_controller_helper.rb
module CoachingControllerHelper
end

app/views/coaching_controller/answer.html.erb
<h1>Your question</h1>
<p><%= @query %></p>
<h1>Answer coach</h1>
<p>cimere ma gueule</p>

<!-- <a href="/coaching_controller/ask">REPOSE UNE QUESTION</a> -->


 <%= link_to "REPOSE UNE QUESTION", coaching_controller_ask_path%>

app/views/coaching_controller/ask.html.erb
<form action="/coaching_controller/answer">
  <label for="question">Speak to your coach</label>
  <input type="text" id="question" name="query" placeholder="what time is it?">
  <input type="submit" value="Go on!">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stupidcoaching</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>